"""test migration 3

Revision ID: 0d91d9cdd856
Revises: 873f96705126
Create Date: 2022-12-28 17:50:00.497525

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0d91d9cdd856'
down_revision = '873f96705126'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
