"""test migration 2

Revision ID: 873f96705126
Revises: 1db4c2e84f48
Create Date: 2022-12-28 17:47:27.984041

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '873f96705126'
down_revision = '1db4c2e84f48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'nickname')
    # ### end Alembic commands ###
