"""added null type to committees

Revision ID: a7bdc9041a8f
Revises: e14b57ee335f
Create Date: 2023-01-08 23:57:49.093440

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a7bdc9041a8f'
down_revision = 'e14b57ee335f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
