"""added additional emergency contacts fields

Revision ID: e14b57ee335f
Revises: f110faac5cd6
Create Date: 2023-01-08 22:01:30.436041

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e14b57ee335f'
down_revision = 'f110faac5cd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('emergency_contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('member', sa.Column('emergency_contact_relationship', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('member', sa.Column('emergency_contact_phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'emergency_contact_phone_number')
    op.drop_column('member', 'emergency_contact_relationship')
    op.drop_column('member', 'emergency_contact_name')
    # ### end Alembic commands ###
